export const TYPE_COLOR = {
  normal: { value: "#707576", type: "dark" },
  fighting: { value: "#BD581A", type: "dark" },
  flying: { value: "#23809B", type: "dark" },
  poison: { value: "#9D5DAE", type: "dark" },
  ground: { value: "#857633", type: "dark" },
  rock: { value: "#897414", type: "dark" },
  bug: { value: "#5C8034", type: "dark" },
  ghost: { value: "#7b62a3", type: "dark" },
  steel: { value: "#617B7C", type: "dark" },
  fire: { value: "#E22423", type: "dark" },
  water: { value: "#357CAA", type: "dark" },
  grass: { value: "#9bcc50", type: "light" },
  electric: { value: "#eed535", type: "light" },
  psychic: { value: "#D42E90", type: "dark" },
  ice: { value: "#51c4e7", type: "light" },
  dragon: { value: "#377DA2", type: "dark" },
  dark: { value: "#4A4A4A", type: "dark" },
  fairy: { value: "#fdb9e9", type: "light" },
  unknown: { value: "#707576", type: "dark" },
  shadow: { value: "#4A4A4A", type: "dark" },
};
